### ISSUE TITLE
custom data training

### ISSUE THREAD

**Issue by chillum-codeX** [liruiw/Dec-SSL#1]
hey
how to train on custom data

**Comment by liruiw** [comment]
Hey, It'd be similar to other learning pipelines where you would need to modify the [dataset](https://github.com/liruiw/Dec-SSL/blob/main/src/utils.py#L290).

**Comment by chillum-codeX** [comment]
Can you please give an example like I want to use covid images datatset, how could i

**Comment by liruiw** [comment]
This question is not unique to this codebase. I would recommend checking out online tutorial such as [1](https://www.learnpytorch.io/04_pytorch_custom_datasets/) and [2](https://towardsdatascience.com/custom-dataset-in-pytorch-part-1-images-2df3152895)

**Comment by chillum-codeX** [comment]
sure i will and let you know
